### ISSUE TITLE
Add Stick automation trigger

### ISSUE THREAD

**Issue by nyancrimew** [ArdenButterfield/Empy#1]
add an automation parameter to cause sticking, to allow for precise timing and duration of sticking in sound design rather than entirely just rng based, i assume this is currently already possible with low stick duration and automating stick probability but this feels rather janky to me, a boolean trigger for sticking would make this much more intuitive

**Comment by ArdenButterfield** [comment]
@nyancrimew I love that idea! I added a simple boolean trigger button, check out the [latest release](https://github.com/ArdenButterfield/Empy/releases/tag/v1.0.1) for it!
